const data = {
  products: [
    {
      lostItemId: 1,
      itemLost: "Izekiel",
      category: "human",
      brand: "pakboi",
      primaryColor: "white?",
      secondaryItemColor: "black",
      dateLost: "August 05, 2021",
      timeLost: "11:00AM",
      image: "/images/kiel.PNG",
      addInfo: "mataba",
      placeLocation: "park",
      zipCode: "2100",
      mapLocation: "sto. domingo",
      firstName: "Izekiel",
      lastName: "David",
      phoneNumber: "0999999999",
      email: "sapusomo@gmail.com",
    },
    {
      lostItemId: 2,
      itemLost: "Denzel",
      category: "human",
      brand: "ritshkid",
      primaryColor: "white",
      secondaryItemColor: "black",
      dateLost: "January 02, 2022",
      timeLost: "12:00AM",
      image: "/images/denzel.PNG",
      addInfo: "b a o",
      placeLocation: "hotel",
      zipCode: "2200",
      mapLocation: "sto. domingo",
      firstName: "Denzel",
      lastName: "Manangu",
      phoneNumber: "09888888888",
      email: "progmer@gmail.com",
    },
    {
      lostItemId: 3,
      itemLost: "Biniboi",
      category: "Programmer",
      brand: "flutter",
      primaryColor: "brown",
      secondaryItemColor: "black",
      dateLost: "February 14, 2022",
      timeLost: "12:00PM",
      image: "/images/bin.PNG",
      addInfo: "wanter robin",
      placeLocation: "motel",
      zipCode: "2300",
      mapLocation: "sto. domingo",
      firstName: "Robin",
      lastName: "Serrano",
      phoneNumber: "09777777777",
      email: "salsalero@gmail.com",
    },
    {
      lostItemId: 1,
      itemLost: "Dog",
      category: "Animal",
      brand: "Husky",
      primaryColor: "white",
      secondaryItemColor: "gray",
      dateLost: "August 05, 2021",
      timeLost: "11:00AM",
      image:
        "https://th.bing.com/th/id/OIP.V4EaoGIWH9Lx7Ja9bdz-TQHaHa?pid=ImgDet&rs=1",
      addInfo: "8 yrs old",
      placeLocation: "park",
      zipCode: "2100",
      mapLocation: "sto. domingo",
      firstName: "Izekiel",
      lastName: "David",
      phoneNumber: "0999999999",
      email: "sapusomo@gmail.com",
    },
    {
      lostItemId: 2,
      itemLost: "bag",
      category: "bag",
      brand: "jansport",
      primaryColor: "pink",
      secondaryItemColor: "violet",
      dateLost: "January 02, 2022",
      timeLost: "12:00AM",
      image:
        "https://cdn.notonthehighstreet.com/fs/b9/84/b4f2-f79d-4d13-b535-a4ef440eb1c9/original_wombat-luxury-leather-multi-pocket-travel-bag.jpg",
      addInfo: "leather",
      placeLocation: "hotel",
      zipCode: "2200",
      mapLocation: "sto. domingo",
      firstName: "Denzel",
      lastName: "Manangu",
      phoneNumber: "09888888888",
      email: "pwetmo@gmail.com",
    },
    {
      lostItemId: 3,
      itemLost: "1000000 Pesos",
      category: "Cash",
      brand: "Php",
      primaryColor: "blue",
      secondaryItemColor: "white",
      dateLost: "February 14, 2022",
      timeLost: "12:00PM",
      image:
        "https://th.bing.com/th/id/R.f7f2850e0c358aed2b1383929083db55?rik=fY0KPdtexSSXkA&riu=http%3a%2f%2f3.bp.blogspot.com%2f-U9W7ZbpNNBo%2fUE1jZ0FTYKI%2fAAAAAAAAA4s%2fCRp7wEx7BT0%2fs1600%2fObverse1kNDS.jpg&ehk=R8%2fYQr%2b7ZFu1UHG4ncQXwwU0JstMqJnmr3r6RqalAQY%3d&risl=&pid=ImgRaw&r=0",
      addInfo: "balik nyo pera ko",
      placeLocation: "motel",
      zipCode: "2300",
      mapLocation: "sto. domingo",
      firstName: "Robin",
      lastName: "Serrano",
      phoneNumber: "09777777777",
      email: "salsalero@gmail.com",
    },
  ],
};

export default data;
